### ISSUE TITLE
Remove NativeLibraryLoader paths on DNX

### ISSUE THREAD

**Issue by bricelam** [aspnet/Microsoft.Data.Sqlite#128]
~~Blocked on aspnet/dnx#402~~
~~Blocked on aspnet/dnx#3119~~

**Comment by bricelam** [comment]
After this, we should be able to get away with just two assemblies: `net45` and `dotnet`

**Comment by natemcmaster** [comment]
:watch: https://github.com/aspnet/dnx/pull/3049

**Comment by natemcmaster** [comment]
@bricelam dnx  has added support for native dlls. We are going to have some problems because we've been using the `runtimes/win10-x__` folder for UAP libraries, but DNX attempts to load these on desktop/coreclr too. (See https://github.com/aspnet/Microsoft.Data.Sqlite/tree/namc/nativedll)

**Comment by bricelam** [comment]
Sounds like a bug. I thought win8, win81 & win10 were explicitly about WinRT. Non-WinRT should use win or win7.

**Comment by natemcmaster** [comment]
> Sounds like a bug. I thought win8, win81 & win10 were explicitly about WinRT. Non-WinRT should use win or win7. 

/cc @moozzyk @muratg how does the native library loading handle the various windows RIDs?

**Comment by muratg** [comment]
@moozzyk is the best person to answer, but he'll be out this week.  @anurse may have some insight.

**Comment by moozzyk** [comment]
@natemcmaster / @bricelam - forgive my ignorance but is there any difference between UAP and onecore? Because if there is we don't have any means to detect this. Currently we just return the version that we got from `GetVersionEx` but we added a manifest to get the actual version so that we can create "correct" RIDs (i.e. to prevent win8.1/win10 be reported as win8). I think I saw once that for Win10 IoT you need to link against onecoreuap.lib or onecore.lib depending on what app you are writing but how express this in one package if they both can run on the same OS? I guess this topic may require more design/discussion...

**Comment by natemcmaster** [comment]
@moozzyk UAP augments .net core with WinRT APIs.  (I think this is what you are asking, but I'm not quite sure....)

The native library we need for SQLite on UAP is build against WinRT and is different from than the native library for desktop/CoreCLR. 

To be clear, the problem I have right now is that if I include the UAP native library in `runtimes/win10-x86/native/sqlite3.dll`, DNX will not load `runtimes/win7-x86/native/sqlite3.dll`

**Comment by natemcmaster** [comment]
Now failing on dnx-coreclr (only coreclr):

Using dnx 1.0.0-rc1-16031

```
System.DllNotFoundException: Unable to load DLL 'C:\Users\namc\dev\microsoft.data.sqlite\src\Microsoft.Data.Sqlite\runtimes\win10-x86\native\sqlite3.dll': This operation is only valid in the context of an app container.
```

**Comment by davidfowl** [comment]
Much improved error. I think this is by design. We need a RID for winrt

**Comment by moozzyk** [comment]
:+1:

**Comment by ericstj** [comment]
It doesn't make sense to block load of non-APPX dlls in WinRT.  APPX bit should be required on the EXE, optional on DLL.  
- DLL with APPX bit should only load in app container since some folks might want to do this to reduce the attack surface of a native component.  
- DLL without should be permitted to load in or out of app container.  

Instead Windows enforces the APPX bit on all code (EXE and DLL) in app container and no APPX bit on all code out of app container.  The result is that there is no way to create a "windows" dll.  You have to build twice: even if the code is identical; even if you don't want the safeguard of only running in app container.  I think the right fix for the ecosystem is for Windows to relax this requirement.  I think the only place the requirement is enforced is the WACK (store certification process) but I could be wrong.  At least when I test locally I am able to run DLLs without the APPX bit in store apps in the app container.

We can add the RID and let people cross-compile all native code for inside/outside app-container but that seems like the wrong thing to do.

**Comment by moozzyk** [comment]
@ericstj - it's not about blocking loading. I think the question here is how to ship a NuGet package that contains a separate native dll for winrt and win. Currently we have just one RID so both versions would have to be in the same folder. But then the names of dlls would have to be different so how you are supposed to use the `DllImport` attribute where you need to pass the name of the native lib?

**Comment by ericstj** [comment]
WinRT API is represented in the TFM. UAP10.0 represents that WinRT API.  RID is discrete so it doesn't scale to versions as granular as WinRT  (10.x.y where x.y changes every couple months).  TFM does since it is continuous.  If you actually depend on WinRT API and you want the package manager to select a different DLL based on WinRT API (+version) then you should use the TFM to represent that.  To avoid the managed compiler referencing the native dll use the ref folder.  
```
ref\uap10.0\foo.dll
runtimes\win10-x86\lib\uap10.0\foo.dll
runtimes\win10-x86\lib\uap10.0\native.dll
runtimes\win10-x64\lib\uap10.0\foo.dll
runtimes\win10-x64\lib\uap10.0\native.dll
```
The duplication here is unfortunate, but a fallout of the NuGet design to model RIDs as discrete opaque strings and the lack of a TFM in the native asset pattern (can't do runtimes/rid/native/tfm/)/

The APPX bit discussion may not be relevant here since you actually depend on WinRT and already wish to cross compile.  If you did lightup for WinRT and shared the same native implementation for win32 and winRT you'd be blocked by the APPX bit problem.

**Comment by moozzyk** [comment]
Thanks @ericstj . Need to take a look how we handle UAP10.0 and probably talk to @anurse but it seems that what we have could be sufficient to make this scenario work without introducing a new RID.

**Comment by davidfowl** [comment]
@lodejard @loudej Did we ever look at tfm specific native dlls?

**Comment by bricelam** [comment]
Made some progress in [bricelam:uwp](https://github.com/aspnet/Microsoft.Data.Sqlite/compare/aspnet:dev...bricelam:uwp), but DNX isn't paying ball. Luckily, it seems unrelated to using the package structure proposed by @ericstj.

**Comment by bricelam** [comment]
Proposed package structure didn't work on UWP. I get the following error.

> Payload contains two or more files with the same destination path 'sqlite3.dll'. Source files: 
C:\Users\bricelam\.nuget\packages\Microsoft.Data.Sqlite\1.0.0-t151102215934\runtimes\win-x86\native\sqlite3.dll
C:\Users\bricelam\.nuget\packages\Microsoft.Data.Sqlite\1.0.0-t151102215934\runtimes\win10-x86\lib\uap10.0\sqlite3.dll

`project.lock.json` is referencing both.

```JSON
{
  "targets": {
    "UAP,Version=v10.0/win10-x86": {
      "Microsoft.Data.Sqlite/1.0.0-t151102215934": {
        "runtime": {
          "runtimes/win10-x86/lib/uap10.0/sqlite3.dll": {}
        },
        "native": {
          "runtimes/win-x86/native/sqlite3.dll": {}
        }
      }
    }
  }
}
```

**Comment by ericstj** [comment]
I think you have targets that are adding different content at the same time as project.json resolution.

**Comment by bricelam** [comment]
Targets only run if project.json isn't present. To be extra sure, I removed the targets completely and tried again but got the same result.

**Comment by ericstj** [comment]
Oh, sorry missed that.  If you are using lib in one place you should use lib in the other as well.  Lib and native each get unique hit-testing.  Instead of runtimes/win-x86/native you could use runtimes/win-x86/lib/any.

**Comment by bricelam** [comment]
@moozzyk @davidfowl Will DNX look for native libraries under `lib`?

**Comment by bricelam** [comment]
Maybe patching with MSBuild on UWP will be best: Let NuGet find a Win32 version then replace it with the correct WinRT version.

**Comment by moozzyk** [comment]
@bricelam With package references dnx does not check paths from the `native` section - it uses them relative to the project location. The idea is that it is on the restore command to put correct things in the `native` section. dnx does not read the `runtime` section for native lib loading.

**Comment by bricelam** [comment]
Nailed it... #170 MSBuild FTW
