### ISSUE TITLE
money type

### ISSUE THREAD

**Issue by sady4850** [aspnet/Microsoft.Data.Sqlite#233]
Hi guys,

Consider the following code:

            using (SqliteConnection sqLiteConnection = new SqliteConnection("Data Source=:memory:")) {
                sqLiteConnection.Open();
                IDbCommand command = sqLiteConnection.CreateCommand();
                command.CommandText = @"create table Product (
                                        ListPrice         money            not null
                                    );
                                    insert into product values (1.1);

                                   ";
                command.ExecuteNonQuery();

                command.CommandText = "SELECT * from Product";

                using (var reader = command.ExecuteReader()) {
                    for (int i = 0; i < reader.FieldCount; i++) {
                        Console.WriteLine("Column Name: {0}, Column Type: {1}", reader.GetName(i), reader.GetFieldType(i));
                    }
                }
            }

For the money column type a reader gives double type. Running the same code on the classic System.Data.SQLite provider [https://www.nuget.org/packages/System.Data.SQLite/](url)  gives decimal type. 

Can you please confirm is this a deliberate change/feature or bug ?

**Comment by natemcmaster** [comment]
You are getting double because the SQLite engine is storing `1.1` as SQLITE_FLOAT. This is a deliberate feature because SQLite columns are not strongly typed (see https://www.sqlite.org/datatype3.html). [SqliteDataReader](https://github.com/aspnet/Microsoft.Data.Sqlite/blob/c4e9cd2ec6def2e1c8c242a168f535fee4798f59/src/Microsoft.Data.Sqlite/SqliteDataReader.cs#L274) relies on SQLite itself to identify datatypes. (If you want the low-level details, see https://www.sqlite.org/c3ref/c_blob.html and https://www.sqlite.org/c3ref/column_blob.html)

**Comment by bricelam** [comment]
Agreed, this is deliberate. Unlike `System.Data.SQLite`, we don't apply any additional semantics to column type names. However, if you call `reader.GetDecimal()`, you should still get a `decimal` value.
