### ISSUE TITLE
Include Xamarin Android and iOS in NuGet Packages

### ISSUE THREAD

**Issue by dvoituron** [aspnet/Microsoft.Data.Sqlite#255]
I tried successfully your excellent new library with Xamarin Andoid. But I need to add a reference manually. Can you configure your NuGet package definition to include **MonoAndroid** and **Xamarin.iOS** (see https://developer.xamarin.com/guides/cross-platform/advanced/nuget).
All dependencies are already included in Mono framework.

See here a sample of the NuGet Package Explorer result.

![image](https://cloud.githubusercontent.com/assets/8350694/15454189/521d64ac-2031-11e6-8655-e6beae4a74bb.png)

**Comment by rowanmiller** [comment]
We'll probably just wait for Xamarin to catch up with netstandard NuGet changes, but leaving open to look at post 1.0.0

**Comment by natemcmaster** [comment]
Xamarin has announced support now for .NET Standard. https://blog.xamarin.com/net-standard-library-support-for-xamarin/. Some basic scenarios work, and using Xamarin + Visual Studio I've been able to get a simple Xamarin.iOS/Android app working...

...but with a few hacks. There are still bugs in Microsoft.Data.Sqlite.

### Known issues on Xamarin

- When using Xamarin Studio on macOS: System.Data.Common doesn't unify to System.Data. https://bugzilla.xamarin.com/show_bug.cgi?id=42702
- Relative paths in connection strings fail on Xamarin.iOS/Android https://github.com/aspnet/Microsoft.Data.Sqlite/issues/279
- Installation fails due to nuget bug when installing our dependency on SQLite.Native: "the package does not contain any assembly references or content files that are compatible with that framework." https://github.com/natemcmaster/libsqlite3-package/issues/6

**Comment by wjvii** [comment]
Is there any update now on using EF Core with Xamarin now that Xamarin supports netstandard? I see a few related entries here on GitHub where people are trying to use EF Core with the latest Xamarin supporting netstandard and running into issues and in particular it seems with Microsoft.Data.Sqlite and its related packages.

Specifically Xamarin states they are now supporting netstandard but I keep running into this: Could not install package 'SQLite.Native 3.12.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

So is this an issue with the package or Xamarin because that package on NuGet.org says it is netstandard1.0 compatible.

**Comment by natemcmaster** [comment]
@wjvii this is one of the known issues I referenced in my previous comment: https://github.com/aspnet/Microsoft.Data.Sqlite/issues/255#issuecomment-237616906 (see https://github.com/natemcmaster/libsqlite3-package/issues/6). I am working with the sqlite team to release an update to the SQLite package that resolves the issue.

**Comment by ericsink** [comment]
FWIW, I think this issue might be more complicated than just needing netstandard support.

The NativeMethods/pinvoke stuff might work okay for iOS as long as you're not using any callbacks anywhere.  (I haven't checked.)

But the new rules with Android N make it basically essential to bundle a SQLite library rather than use the one provided by the OS.

Long term, supporting Xamarin probably means dealing with a lot of the same issues as SQLitePCL.raw (which I maintain).

As part of my exploration of this area, I have submitted pull request #292, in which I rip out the current interop stuff and replace it with a SQLitePCL.raw dependency.  For discussion purposes.

**Comment by natemcmaster** [comment]
> The NativeMethods/pinvoke stuff might work okay for iOS as long as you're not using any callbacks anywhere.

We don't yet, but we've played with callbacks and may add them. https://github.com/aspnet/Microsoft.Data.Sqlite/issues/143

> But the new rules with Android N make it basically essential to bundle a SQLite library rather than use the one provided by the OS.

How does SQLitePCL.raw distribute sqlite for Android N?

**Comment by ericsink** [comment]
> How does SQLitePCL.raw distribute sqlite for Android N?

Bundling a native lib for Xamarin.Android requires placing the .so files into an embedded resource in an assembly.

For use with SQLitePCL.raw, I maintain a set of SQLite builds which are called "e_sqlite3", to eliminate ambiguity with the system SQLite.

The id for the e_sqlite3 package containing the embedded library assembly for Android is SQLitePCLRaw.lib.e_sqlite3.android

An implementation of ISQLite3Provider specifies that "e_sqlite3" is the desired library.  Providers are in packages with id starting with SQLitePCLRaw.provider.*

I have bundle packages which, for each target framework or platform, contain dependencies on the lib and the appropriate provider packages.  Plus an init function which injects the provider into the core assembly so everything is ready to go.

**Comment by divega** [comment]
@bricelam are we still planning to do anything about this for 1.1.0-preview1?

**Comment by bricelam** [comment]
I don't think it fits into 1.1.0-preview1, but we could look at it before 1.1.0 RTMs.

**Comment by bricelam** [comment]
After #21, I don't think there'll be anything left to do on our side to support Xamarin.
