### ISSUE TITLE
Char reading problem

### ISSUE THREAD

**Issue by ili** [aspnet/Microsoft.Data.Sqlite#296]
`char` reading is wrong, please find two tests below.
I'v tested with 1.0.0 version. 
Also if I'll use `System.Data.SQLite` in both cases read result would be "1" (type `System.String`)

```cs
		[Test]
		public void CharTest1()
		{
			using (var connection = new SqliteConnection(@"Data Source=Database\TestData.sqlite"))
			{
				connection.Open();
				var command = connection.CreateCommand();

				command.CommandText = "SELECT Cast(@p as char)";
				var p = command.CreateParameter();
				p.Value = '1';
				p.ParameterName = "@p";

				command.Parameters.Add(p);

				var r = command.ExecuteReader();
				r.Read();

				var value = r.GetValue(0);
				Assert.AreNotEqual("49", value, $"{value.GetType().FullName}");
			}
		}

		[Test]
		public void CharTest2()
		{
			using (var connection = new SqliteConnection(@"Data Source=Database\TestData.sqlite"))
			{
				connection.Open();
				var command = connection.CreateCommand();

				command.CommandText = "SELECT @p";
				var p = command.CreateParameter();
				p.Value = '1';
				p.ParameterName = "@p";

				command.Parameters.Add(p);

				var r = command.ExecuteReader();
				r.Read();

				var value = r.GetValue(0);
				Assert.AreNotEqual((long)49, value, $"{value.GetType().FullName}");
			}
		}
```

**Comment by bricelam** [comment]
SQLite can't store `char` values so we cast them to `short` before storing them. Calling `DbDataReader.GetFieldValue<char>()` should allow you to round-trip these values.

Because of [SQLite's dynamic type system](https://www.sqlite.org/datatype3.html) `DbDataReader.GetValue()` (and `.GetValues()`) is quirky. We avoid trying to apply any semantics to the user-defined column type and just look at what the actual value in the database is, and SQLite only supports four types: `TEXT`, `BLOB`, `INT`, `REAL`. Thus that API will only ever return `string`, `byte[]`, `long`, and `double` values. This gets particularly messy with values we have to coerce like `decimal`, `Guid`, `DateTime`, and `TimeSpan`.
