### ISSUE TITLE
Support SQLiteDateFormats=Ticks

### ISSUE THREAD

**Issue by sdcb** [aspnet/Microsoft.Data.Sqlite#312]
- Ticks 
Use the value of DateTime.Ticks.
- ISO8601 
Use the ISO-8601 format. Uses the "yyyy-MM-dd HH:mm:ss.FFFFFFFK" format for UTC DateTime values and "yyyy-MM-dd HH:mm:ss.FFFFFFF" format for local DateTime values).
- JulianDay
The interval of time in days and fractions of a day since January 1, 4713 BC.
- UnixEpoch 
The whole number of seconds since the Unix epoch (January 1, 1970).
- InvariantCulture
Any culture-independent string value that the .NET Framework can interpret as a valid DateTime.
- CurrentCulture
Any string value that the .NET Framework can interpret as a valid DateTime using the current culture.

**Comment by bricelam** [comment]
Currently, we always store `DateTime` values as ISO-8601 strings. We read them using `DateTime.Parse()` so most formats will just work.

Similar to #191, I think we could support reading reading `DateTime` values form `REAL` columns. The most probable unit for these columns is a Julian day since there is a function for that--`julianday(text)`.

All the others could be handled by the client by reading the string or long directly.

**Comment by rowanmiller** [comment]
@bricelam to file new issue about julianday

**Comment by bricelam** [comment]
Filed #318
