### ISSUE TITLE
UWP unexpected PRAGMA behavior

### ISSUE THREAD

**Issue by achocron** [aspnet/Microsoft.Data.Sqlite#337]
In a UWP application using package version 1.1.0 and sqlite 3.12.3, I am unable to get or set the journal mode. Checking the journal mode with `PRAGMA journal_mode ` returns null, and setting it also returns null.

**Comment by bricelam** [comment]
I confirmed that `sqlite3_stmt_readonly` returns false for this statement (and `PRAGMA mmap_size;`). While I knew we'd get false positives from this method, I didn't anticipate any false negatives like this. The heuristic us used to differentiate between statements that return empty results and statements that don't return results. Since we know we have results, we can bypass the heuristic for these statements.
