### ISSUE TITLE
SqliteParameter not implement ICloneable interface

### ISSUE THREAD

**Issue by tangdf** [aspnet/Microsoft.Data.Sqlite#454]
https://github.com/aspnet/Microsoft.Data.Sqlite/blob/a2b6f5f7d0d9aea44ec2af8060acfc9c5fb37847/src/Microsoft.Data.Sqlite.Core/SqliteParameter.cs#L17-L21

Why the type of  `SqliteParameter` do not implement `ICloneable` interface?

`SqlParameter` implemented`ICloneable` interface。

<https://github.com/dotnet/corefx/blob/83b606b5debad20536a581c425f66f4e9c396ed1/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlParameter.cs#L52-L55>

**Comment by ajcvickers** [comment]
@tangdf We don't intend to implement ICloneable--see [.NET docs](https://docs.microsoft.com/en-us/dotnet/api/system.icloneable?view=netframework-4.7.1). Specifically, "Because callers of Clone() cannot depend on the method performing a predictable cloning operation, we recommend that ICloneable not be implemented in public APIs."

Is there a specific reason you want it?
