### ISSUE TITLE
[Question] - What was fixed in the 2.0.2 nuget release?

### ISSUE THREAD

**Issue by dazinator** [aspnet/Microsoft.Data.Sqlite#492]
Noticed the `2.0.2` update showing on the stable release channel. Is there a way we can see what was fixed in this release?

**Comment by ajcvickers** [comment]
@dazinator It's the list of [issues closed in the 2.0.6 milestone](https://github.com/aspnet/Microsoft.Data.Sqlite/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+milestone%3A2.0.6+). Yes, this is confusing. The reason is that these fixes were released as part of the ASP.NET metapackage, and for consistency across ASP.NET repos the metapackage version is always used.

**Comment by dazinator** [comment]
@ajcvickers Ok cheers.
