### ISSUE TITLE
Use better location as base for relative paths

### ISSUE THREAD

**Issue by sgtfrankieboy** [aspnet/Microsoft.Data.Sqlite#55]
When trying to load a SQLite database from a relative path (`Content\Db\Assets.db`) it will try to load the file from the current process location which is klr.exe instead of the location of the working directory.

**Workarounds**

* Use an absolute path
* Use `PathResolver.ResolveAppRelativePath` from the Configuration project.

**Comment by natemcmaster** [comment]
I can't repo this bug. Was it fixed with #74 ?

**Comment by natemcmaster** [comment]
@sgtfrankieboy are you still experiencing this bug?

**Comment by bricelam** [comment]
In general, we still need to solve the problem. The experience is particularly bad on UWP apps where the default relative path is not writable. We should make things relative to the DataDirectory domain property too, if it's set. Also, if I change the current directory, it shouldn't affect the relative path used in the connection string.

**Comment by natemcmaster** [comment]
Cannot test UWP support until System.Data.Common works for netcore50

**Comment by natemcmaster** [comment]
Instead of doing a magic substitution in the path, I'm in favor of throwing better error messages. On UWP, we throw `Sqlite Error 14: could not open database file`, which doesn't help explain that the folder is inaccessible. We could translate this into a UnauthorizedAccessException which would help users [searching](https://www.bing.com/search?q=windows+store+app+create+file+unauthorizedaccessexception&FORM=AWRE) for a [solution](https://msdn.microsoft.com/en-us/library/windows/apps/hh967755.aspx).

Also, we could provide samples that demonstrate correctly accessing writable folders. E.g.
```c#
new SqliteConnection($"Data Source={ApplicationData.Current.LocalFolder.Path}/test.db");
```

**Comment by natemcmaster** [comment]
@bricelam Can we close this then as 'won't fix'?

**Comment by bricelam** [comment]
@rowanmiller? I'm on the fence. Having relative paths broken by default on UWP still feels like a pit of failure we could address.

**Comment by rowanmiller** [comment]
@natemcmaster @bricelam let's discuss with the team in triage

**Comment by rowanmiller** [comment]
DNX issues are all resolved now. We may consider doing something better for UWP in the future if we see folks hitting issues.

**Comment by natemcmaster** [comment]
*Originally made by @leak on https://github.com/aspnet/EntityFramework/issues/2864*

=================================

Related to https://github.com/aspnet/EntityFramework/issues/2748

Specifying a relative path to a database file does not work, the application dies with 
"SQLite Error 14: 'unable to open database file'".

````
            services.AddEntityFramework()
                .AddSqlite()
                .AddDbContext<AppDbContext>(
                    options => options.UseSqlite("Data Source=db/database.sqlite"));
````

For the "dnx ef" command it already seems to be working (ref https://github.com/aspnet/Microsoft.Data.Sqlite/issues/55)

**Comment by natemcmaster** [comment]
> For the "dnx ef" command it already seems to be working

@leak Please clarify. Does the connection to your database file work when executing `dnx ef`?

**Comment by bricelam** [comment]
My new feelings are that we should...
* Treat all relative paths relative to data directory
* Default the data directory to app root if writable, or local app data if not
* Optionally, implement the `|DataDirectory|` substitution string so users can be explicit

**Comment by natemcmaster** [comment]
I'm still resistant to changing this. IMO this should be handled on the application level using this package. There is too much ambiguity on what the "data directory" should be. e.g. on Windows Apps, is data directory LocalFolder, RoamingFolder, or TemporaryFolder? On DNX, is it ApplicationBasePath or current working directory? And what about Xamarin (iOS and OS X), Linux, console apps, old versions of ASP.NET, etc...? 

That said, I think we can alleviate debugging problems for users such as @leak by expanding the error message to say *exactly* which folder/file it has attempted to open.

**Comment by leak** [comment]
I'll try to summarize the issues i encountered. This might go across multiple issues, but i believe all factor into adjacent design decisions.

An not uncommon app layout would probably look like this:

**MyApp.Data** (Database Model, DbContext, Migrations)
**MyApp.Web** (Web Application, Startup.cs containing EF config and config.json containing the connection string, since the application is supposed to be portable the connection string would probably look like `Data Source=db/database.sqlite`

What I would expect from the toolkit:
1) I can somehow specify a relative path to the database in the config.json
2) When start the application EF picks up this relative path and treats it as being relative to the app root (MyApp.Web project.json location)

for `dnx ef` there are two possibilities:

a) Invokation of `dnx ef migration apply` on the **MyApp.Data** project
- Migrations will be placed in this project: :white_check_mark: Great, as expected
- Startup.cs can be found: :red_circle: It is located in the MyApp.Web which is not referenced in MyApp.Data (see https://github.com/aspnet/EntityFramework/issues/2748)
- DbContext can be found: :white_check_mark: 
- Relative path of the database works: :red_circle: Even if Startup.cs will be found there is still the issue with the relative database path in the MyApp.Web config.json, which would now be treated as relative to MyApp.Data thus not finding the database for applying migrations

b)  Invokation of `dnx ef migration apply` on the **MyApp.Web** project
- Migrations will be placed in this project: :red_circle: On 7.0.0-beta6-13815 I did not find a parameter to change this behavior. I believe they should reside with the model rather than the web application.
- Startup.cs can be found: :white_check_mark: 
- DbContext can be found: :question: Not sure about this, in theory it should be no problem finding it since both project.json and Startup.cs is available
- Relative path of the database works: :white_check_mark: Yep, we're in the same project as if the application was started, so no problem there

So if EF could pick up on relative database path and if the `dnx ef` command is modified to work in either of the described ways there is no need of reintroducing `|DataDirectory|`

**Comment by bricelam** [comment]
@leak Great feedback. The issue here is just one small piece of the puzzle. Issue aspnet/EntityFramework#2294 is to track the overall design-time experience, and make sure all the pieces fit together as expected.

**Comment by natemcmaster** [comment]
As of #161, UWP now automatically adjusts the default relative path to `ApplicationData.Current.LocalFolder`.

**Comment by leak** [comment]
When i run my application from IIS Express the database get created in 
`D:\MyApp\src\MyApp\wwwroot`

and when i create it from a custom dnx command it gets created in
`D:\MyApp\src\MyApp\`

Is there a chance that there is an issue left with relative path in connection with IIS?

**Comment by natemcmaster** [comment]
>  and when I create it from a custom dnx command it gets created in

What is the command you are using?

**Comment by leak** [comment]
Custom command calling Database.EnsureDeleted(), Database.EnsureCreated() and a bit of database seeding.

**Comment by natemcmaster** [comment]
Can you create a new issue with the specific details your connection strings and project setup?
